// Datos del portfolio de Jorge Acedo
window.PORTFOLIO_DATA = {
  name: "Jorge Acedo",
  role: "Software Developer & Data Analyst",
  location: "Cádiz, España",
  email: "jorge.acedo.oliver@gmail.com",
  phone: "+34 662 023 081",
  linkedin: "https://www.linkedin.com/in/jorgeacedooliver/",
  github: "https://github.com/jorgeoliver7",
  instagram: "https://www.instagram.com/jorgeeoliveer/",

  stats: [
    { value: "3+", label: "años de experiencia" },
    { value: "9", label: "proyectos destacados" },
    { value: "10+", label: "tecnologías" },
    { value: "2", label: "perfiles fusionados" },
  ],

  stack: {
    frontend: [
      { name: "React / Next.js", level: 88 },
      { name: "TypeScript", level: 85 },
      { name: "JavaScript", level: 92 },
      { name: "CSS / SASS", level: 85 },
    ],
    backend: [
      { name: "Java / Spring Boot", level: 82 },
      { name: "Node.js", level: 72 },
      { name: "FastAPI", level: 78 },
      { name: "PostgreSQL", level: 80 },
    ],
    data: [
      { name: "Python (Pandas, NumPy)", level: 85 },
      { name: "SQL Avanzado", level: 88 },
      { name: "Visualización (Plotly, Streamlit)", level: 80 },
      { name: "Jupyter Notebooks", level: 86 },
      { name: "IBM Cognos Analytics", level: 70 },
    ],
    tools: [
      { name: "Git / GitHub", level: 90 },
      { name: "Docker", level: 70 },
      { name: "Claude API", level: 78 },
    ],
  },

  projects: [
    {
      id: 1,
      name: "LapSight",
      category: "fullstack",
      desc: "Plataforma de telemetría y gestión 360° para equipos de motorsport: importación multi-formato, tests estadísticos vuelta a vuelta, equipos, calendario y demo en vivo.",
      stack: ["Spring Boot", "FastAPI", "React", "TypeScript", "PostgreSQL"],
      repo: "https://github.com/jorgeoliver7/LapSight",
      live: "lapsight.onrender.com",
      year: "2025",
    },
    {
      id: 2,
      name: "AcedoMotor",
      category: "fullstack",
      desc: "Portal de motos usadas en producción: anuncios verificados, cuenta oficial con tick, moderación, mensajería, subida de fotos y panel admin. Producto real desplegado.",
      stack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Vercel"],
      repo: "https://github.com/jorgeoliver7/acedomotor",
      live: "acedomotor.com",
      year: "2026",
    },
    {
      id: 3,
      name: "Portfolio Interactivo",
      category: "frontend",
      desc: "Este sitio: diseño editorial, animaciones de entrada, modo oscuro/claro, filtros de proyectos y formulario de contacto con Web3Forms.",
      stack: ["HTML5", "CSS3", "JavaScript", "GitHub Pages"],
      repo: "https://github.com/jorgeoliver7/Portfolio-Website",
      live: "jorgeoliver7.github.io/Portfolio-Website",
      year: "2026",
    },
    {
      id: 4,
      name: "RealEstateAnalytics",
      category: "data",
      desc: "Pipeline inmobiliario end-to-end: scraping, ETL, EDA, ML predictivo (Random Forest R² 0.986) y dashboard Streamlit interactivo.",
      stack: ["Python", "Pandas", "scikit-learn", "Streamlit", "Playwright"],
      repo: "https://github.com/jorgeoliver7/RealEstateAnalytics",
      year: "2026",
    },
    {
      id: 5,
      name: "FindYourPrompt",
      category: "fullstack",
      desc: "Plataforma para descubrir, crear y compartir prompts optimizados para IA.",
      stack: ["React", "TypeScript", "AI", "CSS3"],
      repo: "https://github.com/jorgeoliver7/findyourprompt",
      live: "findyourprompt-one.vercel.app",
      year: "2025",
    },
    {
      id: 6,
      name: "Noventa Scouting",
      category: "data",
      desc: "Scouting futbolístico por 90 minutos: métricas per-90, percentiles posicionales, búsqueda por similitud e informes one-page sobre API-Football.",
      stack: ["Python", "FastAPI", "Streamlit", "SQLite"],
      repo: "https://github.com/jorgeoliver7/noventa-scouting",
      year: "2026",
    },
    {
      id: 7,
      name: "F1 Data Analysis",
      category: "data",
      desc: "Análisis completo de F1 con FastF1: ETL, 25+ visualizaciones, telemetría, clasificación multi-sesión y modelos Random Forest + XGBoost.",
      stack: ["Python", "FastF1", "XGBoost", "Streamlit", "Plotly"],
      repo: "https://github.com/jorgeoliver7/F1DataAnalysis",
      year: "2026",
    },
    {
      id: 8,
      name: "iRacing Setup Assistant",
      category: "fullstack",
      desc: "Encuentra, genera y comparte configuraciones óptimas de iRacing por circuito.",
      stack: ["React", "Node.js", "PostgreSQL", "Socket.io"],
      repo: "https://github.com/jorgeoliver7/iRacingSetupAssistant",
      live: "i-racing-setup-assistant.vercel.app",
      year: "2025",
    },
    {
      id: 9,
      name: "Amazon FC Analytics Suite",
      category: "data",
      desc: "Suite de analytics operativos para fulfillment center: patio (Turn Time, OTD), productividad UPH, asistente KPI con Claude API y modelo SQL con 30+ queries avanzadas.",
      stack: ["Python", "SQL", "Plotly", "Claude API", "PostgreSQL"],
      year: "2026",
    },
  ],

  experience: [
    {
      role: "Yard Marshall",
      company: "Amazon Fulfillment Center",
      period: "Nov 2025 — Presente",
      desc: "Coordinación operativa del patio de trailers en un FC de alto volumen. Experiencia directa en el dominio que alimenta mis proyectos de analytics (Turn Time, OTD, dock utilization, productividad UPH). Toma de decisiones en tiempo real con datos operativos.",
      tags: ["Logística", "KPIs Operativos", "Data-Driven", "Amazon FC"],
    },
    {
      role: "Software Developer",
      company: "GrupoOro",
      period: "2023 · 6 meses",
      desc: "Desarrollo integral de aplicaciones web: código, UX/UI, testing y backups. Implementación de gráficos interactivos con Canvas.",
      tags: ["JavaScript", "HTML/CSS", "Python", "Canvas"],
    },
  ],

  education: [
    {
      title: "IBM Data Analyst Professional Certificate",
      institution: "IBM / Coursera",
      year: "2026",
      status: "Completado",
      desc: "Python para ciencia de datos, SQL, Pandas, NumPy, Matplotlib, Seaborn, IBM Cognos Analytics.",
    },
    {
      title: "Grado Superior en Desarrollo de Aplicaciones Web",
      institution: "Universae",
      year: "2024",
      status: "Formación",
      desc: "Desarrollo web con tecnologías modernas, bases de datos y metodologías ágiles.",
    },
    {
      title: "Estudios de Derecho",
      institution: "Universidad de Cádiz",
      year: "2018 — 2023",
      status: "Cursado",
      desc: "Capacidades analíticas, redacción precisa y resolución estructurada de problemas.",
    },
  ],

  languages: [
    { name: "Español", level: "Nativo", pct: 100 },
    { name: "Inglés", level: "B2 Cambridge", pct: 75 },
  ],
};
